/**
 * Requirement Manager API 0.1
 * This is the Requirement Manager API for the web client Source: - [GitHub](https://github.com/ataastar/requirement-manager-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The branch tree
 */
export interface BranchTree { 
    /**
     * The id of the branch
     */
    branchId: number;
    /**
     * The name of the branch
     */
    name: string;
    /**
     * The code of the branch
     */
    code: string;
    /**
     * The id of the parent branch
     */
    parentId: number;
}

