/**
 * Requirement Manager API 0.1
 * This is the Requirement Manager API for the web client Source: - [GitHub](https://github.com/ataastar/requirement-manager-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelError { 
    /**
     * Error message
     */
    error?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * When the error occurred
     */
    timestamp?: string;
}

