/**
 * Requirement Manager API 0.1
 * This is the Requirement Manager API for the web client Source: - [GitHub](https://github.com/ataastar/requirement-manager-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RequirementProperty { 
    /**
     * The type of the property
     */
    type?: string;
    /**
     * The ID of the expression
     */
    expressionId?: number;
    /**
     * The string value of the property
     */
    stringValue?: string | null;
    /**
     * The numeric value of the property
     */
    numberValue?: number | null;
    /**
     * The name of the expression
     */
    expressionName?: string | null;
}

